### ISSUE TITLE
docs:  add configuration documentation for grafana cloud users

### ISSUE THREAD

**Issue by mspiegel31** [grafana/backstage-plugin-grafana-catalog#20]
## Description
It's not clear how to configure this tool for a grafana enterprise deployment, particularly the usage of `stack_slug`.  Please document how to configure the plugin with a grafana enterprise instance!

**Comment by bcotton** [comment]
Currently this plugin requires infrastructure that is only available in Grafana Cloud, specifically the AppPlatform work that was talked about at the last GrafanaCon.
